// Generated by sdks/wire/generate.mjs from the golden JSON Schemas in
// rusty-server/tests/golden/protocol — themselves generated from
// rusty-server/src/protocol.rs. Do not edit; regenerate instead.

/**
 * Every gateway frame, as one closed union keyed by `type`. A frame that parses is one of exactly these shapes; a frame that does not is refused, never partially read.
 */
export type GatewayFrame =
  | {
      /**
       * Client-minted id the response echoes.
       */
      id: string;
      /**
       * Method name, from [`Features::methods`].
       */
      method: string;
      /**
       * Method arguments.
       */
      params?: {
        [k: string]: unknown;
      };
      type: "req";
    }
  | {
      /**
       * The failure, when not.
       */
      error?: ErrorShape | null;
      /**
       * The request id this answers.
       */
      id: string;
      /**
       * Whether the request succeeded.
       */
      ok: boolean;
      /**
       * The result, when `ok`.
       */
      payload?: {
        [k: string]: unknown;
      };
      type: "res";
    }
  | {
      /**
       * Event kind, from [`Features::events`].
       */
      event: string;
      /**
       * Event payload.
       */
      payload?: {
        [k: string]: unknown;
      };
      /**
       * Monotonic per-connection sequence number.
       */
      seq: number;
      type: "event";
    }
  | {
      /**
       * The authority this connection actually holds (never assumed from what was requested).
       */
      auth: GrantedAuth;
      /**
       * What this server can do, as data: the methods a request may name and the events this connection may observe.
       */
      features: Features;
      /**
       * Budgets the connection must respect.
       */
      policy: PolicyBudgets;
      /**
       * The protocol generation the server chose from the client's range.
       */
      protocol: number;
      /**
       * Which server answered.
       */
      server: ServerIdentity;
      /**
       * The initial state: everything after this arrives as sequenced events, so snapshot + gap-free `seq` is a complete view.
       */
      snapshot: ConnectSnapshot;
      type: "hello-ok";
    };

/**
 * The structured error carried by failed responses and refused connects.
 */
export interface ErrorShape {
  /**
   * Stable machine-readable code.
   */
  code: string;
  /**
   * Error-specific detail payload.
   */
  details?: {
    [k: string]: unknown;
  };
  /**
   * Human-readable description.
   */
  message: string;
  /**
   * Server-suggested floor before a retry.
   */
  retry_after_ms?: number | null;
  /**
   * Whether retrying the same frame can succeed.
   */
  retryable?: boolean | null;
}
/**
 * What the connection is allowed to do — the grant, not the request.
 */
export interface GrantedAuth {
  /**
   * The role the credentials resolved to.
   */
  role: string;
  /**
   * The scopes actually granted.
   */
  scopes: string[];
}
/**
 * The server's capability listing, as data a client can branch on.
 */
export interface Features {
  /**
   * Event kinds this connection may observe.
   */
  events: string[];
  /**
   * Request methods this server serves.
   */
  methods: string[];
}
/**
 * Connection budgets. Declared, not discovered: a client that knows the ceilings validates before sending instead of learning them from a dropped connection.
 */
export interface PolicyBudgets {
  /**
   * Most unacknowledged bytes the server buffers before it closes the connection as stalled.
   */
  max_buffered_bytes: number;
  /**
   * Largest frame the server accepts, in bytes.
   */
  max_payload_bytes: number;
  /**
   * Heartbeat interval; a client that misses several ticks should reconnect and re-snapshot.
   */
  tick_interval_ms: number;
}
/**
 * The answering server's identity.
 */
export interface ServerIdentity {
  /**
   * This connection's server-minted id; correlates gateway log lines with client reports.
   */
  conn_id: string;
  /**
   * Server build version.
   */
  version: string;
}
/**
 * The state a connection starts from. Deliberately the same truth the REST surface serves at `/info`: the registered graphs. Everything richer (threads, runs) stays request/response until the sequenced event catalog carries it.
 */
export interface ConnectSnapshot {
  /**
   * The graphs registered on this server.
   */
  graphs: GraphSummary[];
  /**
   * Version of the state this snapshot describes; event frames carry the `seq` that continues from it.
   */
  state_version: number;
}
/**
 * One registered graph, as the snapshot lists it.
 */
export interface GraphSummary {
  /**
   * Declared state channels.
   */
  channels: string[];
  /**
   * Graph name (`POST /threads` binds to it).
   */
  name: string;
}

/**
 * The client's opening message: the protocol range it speaks, who it is, and how it authenticates.
 */
export interface ConnectParams {
  /**
   * Credentials. Absent on an open-mode server.
   */
  auth?: ConnectAuth | null;
  /**
   * Who is connecting.
   */
  client: ClientIdentity;
  /**
   * Newest protocol generation the client understands.
   */
  max_protocol: number;
  /**
   * Oldest protocol generation the client still understands.
   */
  min_protocol: number;
  /**
   * Scopes the client asks for; the grant comes back in [`HelloOk::auth`] and may be narrower.
   */
  scopes?: string[] | null;
}
/**
 * Connect credentials. Mirrors the HTTP surface's `X-Api-Key` scheme — the gateway grants what the same key would be granted over REST.
 */
export interface ConnectAuth {
  /**
   * API key, when the server is not in open mode.
   */
  api_key?: string | null;
}
/**
 * The connecting client's self-description.
 */
export interface ClientIdentity {
  /**
   * Human-readable name, when the client has one.
   */
  display_name?: string | null;
  /**
   * Stable client identifier (e.g. `studio`, `sdk-ts`).
   */
  id: string;
  /**
   * Platform the client runs on (e.g. `web`, `node`, `python`).
   */
  platform: string;
  /**
   * Client build version.
   */
  version: string;
}
