// Generates src/frames.ts from the golden JSON Schemas the Rust
// conformance suite maintains (rusty-server/tests/golden/protocol) —
// the wire is defined once, in rusty-server/src/protocol.rs, and every
// client type is a projection of it. Run `npm run generate` after
// updating the goldens (UPDATE_GOLDEN=1 on the Rust side); the test
// suite fails while the committed output is stale.

import { compile } from "json-schema-to-typescript";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const goldenDir = path.resolve(here, "../../rusty-server/tests/golden/protocol");

const SOURCES = [
  { file: "gateway_frame_schema.json", name: "GatewayFrame" },
  { file: "connect_params_schema.json", name: "ConnectParams" },
];

const HEADER = `// Generated by sdks/wire/generate.mjs from the golden JSON Schemas in
// rusty-server/tests/golden/protocol — themselves generated from
// rusty-server/src/protocol.rs. Do not edit; regenerate instead.

`;

export async function generate() {
  const parts = [];
  for (const { file, name } of SOURCES) {
    const schema = JSON.parse(await readFile(path.join(goldenDir, file), "utf8"));
    parts.push(
      await compile(schema, name, {
        // The wire's objects are closed (serde deny_unknown_fields); a
        // schema that is silent about additionalProperties still means
        // closed here, so no index signatures.
        additionalProperties: false,
        bannerComment: "",
      }),
    );
  }
  return HEADER + parts.join("\n");
}

const invokedDirectly = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  const out = path.join(here, "src", "frames.ts");
  await writeFile(out, await generate());
  console.log(`wrote ${path.relative(process.cwd(), out)}`);
}
