// Studio v2 consumes the gateway wire protocol exactly as generated from the
// Rust types (contracts:gateway-protocol). The artifact is regenerated by
// `cargo run -p rusty-agent-server --bin gateway_protocol_schema`; nothing in
// v2 hand-declares API types (R-X1).
export type * from "../../../../sdks/typescript/src/gateway-protocol";
