// The wire package's two guarantees: the committed types are exactly
// what the golden schemas generate (freshness), and the Rust-serialized
// hello-ok sample satisfies the generated GatewayFrame type
// (round-trip: Rust type → JSON Schema → TS type → Rust bytes).

import assert from "node:assert/strict";
import test from "node:test";
import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { generate } from "../generate.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const pkg = path.resolve(here, "..");
const samplePath = path.resolve(
  pkg,
  "../../rusty-server/tests/golden/protocol/gateway_hello_ok_sample.json",
);

test("committed frames.ts is exactly what the golden schemas generate", async () => {
  const committed = await readFile(path.join(pkg, "src", "frames.ts"), "utf8");
  assert.equal(
    committed,
    await generate(),
    "src/frames.ts is stale — run `npm run generate` and commit the diff",
  );
});

test("the Rust-serialized hello-ok sample satisfies the generated types", async () => {
  const sample = JSON.parse(await readFile(samplePath, "utf8"));
  assert.equal(sample.type, "hello-ok");

  // Embed the sample as a literal in an annotated position: contextual
  // typing narrows the discriminant and excess-property checks make the
  // structural comparison exact. tsc is the assertion.
  const probe = path.join(here, "sample.generated.ts");
  await writeFile(
    probe,
    `// Generated by roundtrip.test.mjs — the Rust-serialized sample as a typed literal.\n` +
      `import type { GatewayFrame } from "../src/frames.js";\n\n` +
      `export const sample: GatewayFrame = ${JSON.stringify(sample, null, 2)};\n`,
  );
  execFileSync(path.join(pkg, "node_modules", ".bin", "tsc"), ["--noEmit", "-p", pkg], {
    stdio: "pipe",
  });
});
