import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import type { RunEvent } from "../contracts";
import {
  deriveRenderIntent,
  deriveRenderIntentFromEvent,
  MAX_INTENT_EXCERPT_CHARS,
  MAX_INTENT_TABLE_ROWS,
  renderIntentSchema,
  TRUNCATION_MARKER,
} from "./renderIntents";

// The shared parity contract: `rusty-core/tests/golden/render_intents.json`
// is generated by the Rust derivation (`UPDATE_GOLDEN=1 cargo test -p
// rusty-agent-runtime --test render_intents`). Every case here asserts the
// TypeScript mirror derives the identical serialized intent — same JSON in,
// same intent out — so a replayed run renders exactly what the live run
// rendered.
// Vitest runs from the studio/ui package root; the golden file lives two
// directories up in the monorepo.
const goldenPath = resolve(process.cwd(), "../../rusty-core/tests/golden/render_intents.json");
const golden = JSON.parse(readFileSync(goldenPath, "utf8")) as {
  version: number;
  cases: { name: string; tool: string; arguments: unknown; result: unknown; intent: unknown }[];
};

describe("render intent parity with the Rust derivation", () => {
  it("covers every union variant across the shared cases", () => {
    const kinds = new Set(golden.cases.map((parityCase) => (parityCase.intent as { kind: string }).kind));
    for (const kind of ["generic", "terminal", "diff", "search", "read", "table", "link", "web"]) {
      expect(kinds.has(kind), `the shared cases must exercise the ${kind} variant`).toBe(true);
    }
  });

  for (const parityCase of golden.cases) {
    it(`derives identically: ${parityCase.name}`, () => {
      const intent = deriveRenderIntent(parityCase.tool, parityCase.arguments, parityCase.result);
      expect(intent).toEqual(parityCase.intent);
      expect(renderIntentSchema.parse(intent)).toEqual(intent);
    });
  }
});

function toolEvent(overrides: Partial<RunEvent>): RunEvent {
  return {
    id: "run-1:3",
    run_id: "run-1",
    thread_id: "thread-1",
    node_id: "tools",
    seq: "3",
    kind: "tool_call",
    effect: "read_only",
    input: { kind: "inline", value: { tool: "calculator", arguments: { operation: "add", left: 1, right: 2 } } },
    output: { kind: "inline", value: { result: 3 } },
    latency_ms: "4",
    tokens: null,
    cost_usd: null,
    status: "ok",
    parent: "run-1:2",
    recorded_at: "2026-08-12T00:00:00Z",
    rawJson: "{}",
    ...overrides,
  };
}

describe("deriveRenderIntentFromEvent", () => {
  it("unpacks the journaled inline request shape", () => {
    expect(deriveRenderIntentFromEvent(toolEvent({}))).toEqual({
      kind: "table",
      columns: ["operation", "left", "right", "result"],
      rows: [["add", "1", "2", "3"]],
      truncated: false,
    });
  });

  it("returns null for non-tool events", () => {
    expect(deriveRenderIntentFromEvent(toolEvent({ kind: "model_call" }))).toBeNull();
  });

  it("renders failures as an honest generic card", () => {
    const intent = deriveRenderIntentFromEvent(toolEvent({
      status: "error",
      output: { kind: "inline", value: { error: "run_cli program `rm` is not in the policy allowlist" } },
    }));
    expect(intent).toEqual({
      kind: "generic",
      tool: "calculator",
      reason: "the tool call failed; the journal carries the error",
      summary: "run_cli program `rm` is not in the policy allowlist",
    });
  });

  it("declines content-addressed payloads instead of guessing", () => {
    const intent = deriveRenderIntentFromEvent(toolEvent({
      output: { kind: "artifact", value: { hash: "ab".repeat(32) } },
    }));
    expect(intent?.kind).toBe("generic");
    expect(intent && intent.kind === "generic" ? intent.reason : "").toContain("content-addressed");
  });
});

describe("derivation bounds and fallback honesty", () => {
  it("clamps terminal streams with the explicit marker", () => {
    const intent = deriveRenderIntent("run_cli", { program: "flood" }, {
      stdout: "x".repeat(MAX_INTENT_EXCERPT_CHARS * 2),
      stderr: "",
      exit_code: 0,
    });
    if (intent.kind !== "terminal") throw new Error("expected a terminal intent");
    expect(intent.truncated).toBe(true);
    expect(intent.stdout.endsWith(TRUNCATION_MARKER)).toBe(true);
    expect([...intent.stdout].length).toBeLessThanOrEqual(MAX_INTENT_EXCERPT_CHARS);
  });

  it("strips control characters but keeps newlines in block text", () => {
    const intent = deriveRenderIntent("run_cli", { program: "p" }, {
      stdout: "esc\u001b[31m kept\nnewline",
      stderr: "",
    });
    if (intent.kind !== "terminal") throw new Error("expected a terminal intent");
    expect(intent.stdout).not.toContain("\u001b");
    expect(intent.stdout).toContain("kept\nnewline");
  });

  it("clamps structural tables at the row ceiling with the flag", () => {
    const rows = Array.from({ length: MAX_INTENT_TABLE_ROWS + 10 }, (_, n) => ({ n }));
    const intent = deriveRenderIntent("acme/flood", {}, rows);
    if (intent.kind !== "table") throw new Error("expected a table intent");
    expect(intent.rows).toHaveLength(MAX_INTENT_TABLE_ROWS);
    expect(intent.truncated).toBe(true);
  });

  it("falls back to generic for unknown shapes and never throws", () => {
    for (const result of [null, {}, "nope", [1, 2], 42]) {
      const intent = deriveRenderIntent("mystery_tool", null, result);
      expect(intent.kind).toBe("generic");
      if (intent.kind !== "generic") throw new Error("unreachable");
      expect(intent.reason.length).toBeGreaterThan(0);
    }
  });
});
