//! The gateway-protocol generation pipeline (EP-04-S01 AC5): the Rust
//! types behind `contracts:gateway-protocol`
//! ([`rusty_api::gateway_protocol`]) generate the JSON Schema bundle the
//! server validates frames against and the TypeScript declarations the
//! client compiles — one source of truth, so a protocol change without a
//! schema change fails the drift gate
//! (`tests/gateway_schema_drift.rs`), not production.
//!
//! Committed artifacts, regenerated by
//! `cargo run -p rusty-agent-server --bin gateway_protocol_schema`:
//!
//! - `rusty-server/schema/gateway-protocol.schema.json` — the validator
//!   bundle: one JSON Schema per protocol type, names sorted, plus the
//!   generator stamp.
//! - `sdks/typescript/src/gateway-protocol.d.ts` — the client types,
//!   rendered by [`render_ts_types`] over the bundle.
//!
//! The TypeScript renderer covers exactly the schema subset the protocol
//! types use — plain string enums, internally tagged enums, serde
//! `flatten` intersections, `Option` fields, `Vec`, scalars, arbitrary
//! JSON — and fails loudly on anything else, so a type that outgrows the
//! subset breaks the build here rather than emitting a silently wrong
//! client.

use std::collections::BTreeMap;
use std::fmt;

use serde_json::{json, Value};

/// The committed schema artifact, relative to the workspace root.
pub const SCHEMA_ARTIFACT: &str = "rusty-server/schema/gateway-protocol.schema.json";

/// The committed TypeScript artifact, relative to the workspace root.
pub const TS_ARTIFACT: &str = "sdks/typescript/src/gateway-protocol.d.ts";

/// The schema bundle: one named schema per protocol type, sorted, plus a
/// generator stamp so the artifact names its own provenance.
pub fn protocol_schema_bundle() -> Value {
    use rusty_api::gateway_protocol as gp;
    let mut types = BTreeMap::new();
    for name in gp::PROTOCOL_TYPES {
        let schema = match *name {
            "Frame" => schemars::schema_for!(gp::Frame),
            "ResponseOutcome" => schemars::schema_for!(gp::ResponseOutcome),
            "Pairing" => schemars::schema_for!(gp::Pairing),
            "TurnLease" => schemars::schema_for!(gp::TurnLease),
            "SteeringVerb" => schemars::schema_for!(gp::SteeringVerb),
            "AdmissionReason" => schemars::schema_for!(gp::AdmissionReason),
            other => panic!("unregistered protocol type: {other}"),
        };
        types.insert(
            (*name).to_owned(),
            serde_json::to_value(&schema).expect("a schemars schema serializes"),
        );
    }
    json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "rusty gateway protocol (contracts:gateway-protocol)",
        "generator": "gateway_protocol_schema (schemars 0.8)",
        "types": types,
    })
}

/// The canonical artifact bytes: pretty-printed, trailing newline, so the
/// drift gate diffs text, not formatting noise.
pub fn schema_artifact_bytes() -> String {
    let bundle = protocol_schema_bundle();
    let mut text = serde_json::to_string_pretty(&bundle).expect("a generated bundle serializes");
    text.push('\n');
    text
}

/// A schema construct outside the renderer's documented subset.
#[derive(Debug)]
pub struct SchemaRenderError(String);

impl fmt::Display for SchemaRenderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "gateway-protocol TS render: {}", self.0)
    }
}

impl std::error::Error for SchemaRenderError {}

fn err<T>(message: impl Into<String>) -> Result<T, SchemaRenderError> {
    Err(SchemaRenderError(message.into()))
}

/// Render the TypeScript declarations for a schema bundle. One exported
/// declaration per protocol type, in sorted order, each preceded by its
/// doc line when the schema carries a `description`.
pub fn render_ts_types(bundle: &Value) -> Result<String, SchemaRenderError> {
    let types = bundle
        .get("types")
        .and_then(Value::as_object)
        .ok_or_else(|| SchemaRenderError("bundle has no `types` object".to_owned()))?;
    let mut out = String::from(
        "/**\n * The gateway wire protocol (contracts:gateway-protocol), generated from the\n \
         * Rust types by `gateway_protocol_schema` — do not edit by hand; regenerate with\n \
         * `cargo run -p rusty-agent-server --bin gateway_protocol_schema`.\n */\n\n",
    );
    for (name, schema) in types {
        out.push_str(&render_named_type(name, schema)?);
        out.push('\n');
    }
    Ok(out)
}

/// Render one named schema as a TS declaration.
fn render_named_type(name: &str, schema: &Value) -> Result<String, SchemaRenderError> {
    let doc = doc_block(schema);
    // Plain string enum → union of literals.
    if let Some(variants) = string_enum(schema) {
        let literals: Vec<String> = variants.iter().map(|v| format!("  | {v:?}")).collect();
        return Ok(format!(
            "{doc}export type {name} =\n{};\n",
            literals.join("\n")
        ));
    }
    // Internally tagged enum (with or without flattened members) →
    // discriminated union of inline objects.
    if schema.get("oneOf").is_some() {
        let members = render_one_of(schema)?;
        return Ok(format!(
            "{doc}export type {name} =\n{};\n",
            members
                .iter()
                .map(|member| format!("  | {member}"))
                .collect::<Vec<_>>()
                .join("\n")
        ));
    }
    // Flat struct → interface with per-field doc lines.
    if schema.get("type").and_then(Value::as_str) == Some("object") {
        let mut body = String::new();
        render_object_fields(schema, 1, &mut body)?;
        return Ok(format!("{doc}export interface {name} {{\n{body}}}\n"));
    }
    err(format!("{name}: schema shape outside the renderer subset"))
}

/// A schema's string-literal `enum`, when every variant is a string.
fn string_enum(schema: &Value) -> Option<Vec<&str>> {
    let variants: Vec<&str> = schema
        .get("enum")?
        .as_array()?
        .iter()
        .map(Value::as_str)
        .collect::<Option<Vec<_>>>()?;
    Some(variants)
}

/// Render a `oneOf` member list, where a member may itself be a flattened
/// intersection (base properties plus a nested `oneOf`, the serde
/// `flatten` shape schemars emits for `Frame::Response`).
fn render_one_of(schema: &Value) -> Result<Vec<String>, SchemaRenderError> {
    let variants = schema
        .get("oneOf")
        .and_then(Value::as_array)
        .ok_or_else(|| SchemaRenderError("oneOf is not an array".to_owned()))?;
    variants.iter().map(render_intersection).collect()
}

/// Render one union member: a plain string-literal arm, or its own
/// properties intersected with any nested `oneOf` (the flattened-outcome
/// case).
fn render_intersection(schema: &Value) -> Result<String, SchemaRenderError> {
    if let Some(variants) = string_enum(schema) {
        return Ok(variants
            .iter()
            .map(|v| format!("{v:?}"))
            .collect::<Vec<_>>()
            .join(" | "));
    }
    let mut parts = Vec::new();
    if schema.get("properties").is_some() {
        parts.push(render_inline_object(schema)?);
    }
    if schema.get("oneOf").is_some() {
        let members = render_one_of(schema)?;
        let joined = if members.len() == 1 {
            members[0].clone()
        } else {
            format!("({})", members.join(" | "))
        };
        parts.push(joined);
    }
    if parts.is_empty() {
        return err("union member carries neither properties nor oneOf".to_owned());
    }
    Ok(parts.join(" & "))
}

/// One rendered field: its folded doc line and its declaration text.
struct FieldLine {
    doc: Option<String>,
    text: String,
}

/// Walk an object schema's properties once: optionality from `required`,
/// the TS type from [`render_field_type`], docs from `description`.
fn object_fields(schema: &Value) -> Result<Vec<FieldLine>, SchemaRenderError> {
    let properties = schema
        .get("properties")
        .and_then(Value::as_object)
        .ok_or_else(|| SchemaRenderError("object schema without properties".to_owned()))?;
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|list| list.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let mut fields = Vec::new();
    for (field, field_schema) in properties {
        let doc = field_schema
            .get("description")
            .and_then(Value::as_str)
            .and_then(|doc| {
                let summary = doc.lines().next().unwrap_or("").trim();
                (!summary.is_empty()).then(|| format!("/** {summary} */"))
            });
        let optional = if required.contains(&field.as_str()) {
            ""
        } else {
            "?"
        };
        let ts = render_field_type(field_schema)?;
        fields.push(FieldLine {
            doc,
            text: format!("{field}{optional}: {ts};"),
        });
    }
    Ok(fields)
}

/// Render an object schema as a single-line inline literal
/// (`{ frame: "request"; id: number }`) — the union-member form. Doc
/// lines stay on the interface form; members stay scannable.
fn render_inline_object(schema: &Value) -> Result<String, SchemaRenderError> {
    let fields = object_fields(schema)?;
    let texts: Vec<&str> = fields.iter().map(|field| field.text.as_str()).collect();
    Ok(format!("{{ {} }}", texts.join(" ")))
}

/// Render an object schema's fields, one per line at `indent` levels,
/// each preceded by its doc line when described.
fn render_object_fields(
    schema: &Value,
    indent: usize,
    out: &mut String,
) -> Result<(), SchemaRenderError> {
    let pad = "  ".repeat(indent);
    for field in object_fields(schema)? {
        if let Some(doc) = field.doc {
            out.push_str(&pad);
            out.push_str(&doc);
            out.push('\n');
        }
        out.push_str(&pad);
        out.push_str(&field.text);
        out.push('\n');
    }
    Ok(())
}

/// Render one property schema as a TS type.
fn render_field_type(schema: &Value) -> Result<String, SchemaRenderError> {
    // Arbitrary JSON: schemars emits `true` or `{}` for serde_json::Value,
    // or — when the field carries a doc line — an object holding only the
    // `description`.
    if schema.is_boolean()
        || schema
            .as_object()
            .is_some_and(|o| o.keys().all(|key| key == "description"))
    {
        return Ok("unknown".to_owned());
    }
    // String literals (the tag discriminant) or free enums.
    if let Some(variants) = string_enum(schema) {
        return Ok(variants
            .iter()
            .map(|v| format!("{v:?}"))
            .collect::<Vec<_>>()
            .join(" | "));
    }
    if let Some(items) = schema.get("items") {
        return Ok(format!("{}[]", render_field_type(items)?));
    }
    match schema.get("type") {
        Some(Value::String(kind)) => match kind.as_str() {
            "string" => Ok("string".to_owned()),
            "integer" | "number" => Ok("number".to_owned()),
            "boolean" => Ok("boolean".to_owned()),
            "object" => render_inline_object(schema),
            other => err(format!("unsupported field type: {other}")),
        },
        // `Option<T>`: schemars emits `{"type": ["string", "null"]}`.
        Some(Value::Array(kinds)) => {
            let rendered: Result<Vec<String>, _> = kinds
                .iter()
                .map(|kind| match kind.as_str() {
                    Some("null") => Ok("null".to_owned()),
                    Some("string") => Ok("string".to_owned()),
                    Some("integer") | Some("number") => Ok("number".to_owned()),
                    Some("boolean") => Ok("boolean".to_owned()),
                    other => err(format!("unsupported nullable arm: {other:?}")),
                })
                .collect();
            Ok(rendered?.join(" | "))
        }
        other => err(format!("unsupported field schema: {other:?}")),
    }
}

/// Fold a schema's `description` into a TS doc block.
fn doc_block(schema: &Value) -> String {
    let Some(description) = schema.get("description").and_then(Value::as_str) else {
        return String::new();
    };
    let summary = description.lines().next().unwrap_or("").trim();
    if summary.is_empty() {
        return String::new();
    }
    format!("/** {summary} */\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_bundle_names_every_protocol_type_sorted() {
        let bundle = protocol_schema_bundle();
        let names: Vec<&str> = bundle["types"]
            .as_object()
            .unwrap()
            .keys()
            .map(String::as_str)
            .collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        assert_eq!(names, sorted, "the bundle iterates sorted for stable diffs");
        assert_eq!(
            names.len(),
            rusty_api::gateway_protocol::PROTOCOL_TYPES.len()
        );
    }

    #[test]
    fn the_ts_render_covers_the_protocol_shapes() {
        let bundle = protocol_schema_bundle();
        let ts = render_ts_types(&bundle).unwrap();
        // The discriminated union with the tag literal (inline members
        // carry no doc lines — docs live on the interface form).
        assert!(ts.contains("  | { frame: \"request\";"), "{ts}");
        assert!(ts.contains("idempotency_key?: string | null;"), "{ts}");
        assert!(ts.contains("params: unknown;"), "{ts}");
        // The flattened outcome intersects the base object.
        assert!(ts.contains("} & ({ ok:"), "{ts}");
        // Plain string enums.
        assert!(ts.contains("| \"followup\""), "{ts}");
        assert!(ts.contains("| \"lease_held\""), "{ts}");
        // The flat struct interface with timestamps as strings.
        assert!(ts.contains("export interface TurnLease {"), "{ts}");
        assert!(ts.contains("session_id: string;"), "{ts}");
    }

    #[test]
    fn a_shape_outside_the_subset_fails_loudly() {
        let bundle = json!({
            "types": {
                "Odd": {"type": "array", "items": {"type": "string"}}
            }
        });
        let error = render_ts_types(&bundle).unwrap_err();
        assert!(error.to_string().contains("Odd"), "{error}");
    }

    #[test]
    fn a_type_change_drifts_the_render() {
        let bundle = protocol_schema_bundle();
        let baseline = render_ts_types(&bundle).unwrap();
        let mut mutated = bundle.clone();
        mutated["types"]["AdmissionReason"]["oneOf"]
            .as_array_mut()
            .unwrap()
            .push(json!({"enum": ["retroactive"], "type": "string"}));
        assert_ne!(
            render_ts_types(&mutated).unwrap(),
            baseline,
            "a protocol change must change the generated client"
        );
    }
}
